### ISSUE TITLE
Make Yolov8.NET multiplatform

### ISSUE THREAD

**Issue by Miro382** [sstainba/Yolov8.Net#10]
Hi, the current issue for this interface is that it uses System.Drawing.Image, which only works exclusively on the Windows platform. For the new multiplatform .NET, this is a huge disadvantage. It would be better to be able to use, for example, ImageSharp.
https://github.com/SixLabors/ImageSharp

**Comment by xiaoguaishoubaobao** [comment]
> Hi, the current issue for this interface is that it uses System.Drawing.Image, which only works exclusively on the Windows platform. For the new multiplatform .NET, this is a huge disadvantage. It would be better to be able to use, for example, ImageSharp. https://github.com/SixLabors/ImageSharp

I think you're right. Strongly recommend supporting multiple platforms

**Comment by felaray** [comment]
I hope this also.

**Comment by sstainba** [comment]
I've updated the package to remove the dependency on System.Drawing.  It now depends on ImageSharp.
