### ISSUE TITLE
Training issues

### ISSUE THREAD

**Issue by m7mdhka** [sstainba/Yolov8.Net#11]
Hello, when I'm train Yolo8m.pt and then convert it to onnx, I'm facing an issues. like this:
**System.AggregateException: 'One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (Index was outside the bounds of the array.)) (One or more errors occurred. (Index was outside the bounds of the array.)))'**

What is the best way to train on custom dataset?! and how to put the custom model with it classes?

**Comment by sstainba** [comment]
This question should be posted to the ultralytics github.  Your issue has nothing to do with this code/project.
