### ISSUE TITLE
Why does it take longer to predict using the GPU than using the CPU？

### ISSUE THREAD

**Issue by zzzdddyyy** [sstainba/Yolov8.Net#13]
It takes hundreds of milliseconds to predict an image using the CPU,but using the GPU to predict an image takes a few seconds.it doesn't make sense.

**Comment by hukjin** [comment]
same .. did you fix this problem?

**Comment by zzzdddyyy** [comment]
Yes，I found out why this was happening.GPU computation is different from CPU computation.The first time to import a model using the GPU will consume a lot of time,In the second operation, the model has been loaded and only takes a little time to complete.Therefore, the real usage scenario is different from the test mode, and the GPU model will be loaded first when the program starts.
Here are the results:
![1685843925932](https://github.com/sstainba/Yolov8.Net/assets/32119468/8a2d8727-93d0-4985-ac6f-d7cefae74666)
