### ISSUE TITLE
using GPU instead of CPU

### ISSUE THREAD

**Issue by Steven-L-42** [sstainba/Yolov8.Net#17]
Why does the prediction use CPU instead of GPU?

elapsed time for a 640x image is ~1600ms.
Thats really slow since iam using a yolov8s modell.

if i predict it in CLI with GPU i always have around 25-30ms.

**Comment by Steven-L-42** [comment]
activate cuda on YoloV8Predictor.Create also just cause errors:


Microsoft.ML.OnnxRuntime.OnnxRuntimeException: "[ErrorCode:RuntimeException] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1069 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\ShiiikK\source\repos\YoloV8WPF\YoloV8WPF\bin\Debug\net6.0-windows\runtimes\win-x64\native\onnxruntime_providers_cuda.dll"

i tried onnx GPU version 1.13 -> newest. 

Cuda version installed and tried 11.4, 11.6, 11.7 

with information from this page: https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html

**Comment by pocki** [comment]
The LoadLibrary Error seems to be similar to this issue: [https://github.com/cassiebreviu/StableDiffusion/issues/4]

**Comment by sstainba** [comment]
You must have CUDNN installed as well to support GPU processing.  Make sure the version you install matches the CUDA driver version you have.  

The first prediction is slower due to the time it take to load the model into memory.  Subsequent predictions are significantly faster.

Please check the closed issues, #7 and #13

**Comment by Steven-L-42** [comment]
_Which version you recommend for your package?_ i tried now also 

### CUDA 11.6, 

### onnx.runtime.gpu 1.14, 1.13.1 and 1.12.1 and lower

### onnx.runtime 1.14, 1.13.1 and 1.12.1 and lower

### CUDNN 8.5.0.96 (Windows)

### Microsoft.ML.OnnxRuntime.Managed 1.15.1 (since it is a dependency for your package)


**the only difference is if i load 1.14 onnx.gpu i get this error:** `System.EntryPointNotFoundException: "Unable to find an entry point named 'OrtSessionOptionsAppendExecutionProvider_CUDA' in DLL 'onnxruntime'."`

**and if i load <1.13.1 i get this:** `System.TypeInitializationException: "The type initializer for 'Microsoft.ML.OnnxRuntime.NativeMethods' threw an exception."
`

_Do onnx.runtime and onnx.runtime.gpu need always the same versions?_
if i take onnx.runtime.gpu 1.12.1 and onnx.runtime 1.13.1, my program is shown up, but if i start my function it crashs without any Exception.
Here the line where it crashs, i tried to catch it but they wont throw any exception. They just kill my Program: 


```
graphics.CopyFromScreen(wh.Item2.X, wh.Item2.Y, 0, 0, new System.Drawing.Size(wh.Item1.X, wh.Item1.Y));
var image = v8.ConvertBitmapToImageSharpImage(screenshot);
Prediction[] predictions = null;
try
{
    predictions = v8.yolo.Predict(image); // After reach this point it kills my program
}catch (Exception ex) 
{ }
```

**Comment by freefer** [comment]
> _Which version you recommend for your package?_ i tried now also
> 
> ### CUDA 11.6,
> ### onnx.runtime.gpu 1.14, 1.13.1 and 1.12.1 and lower
> ### onnx.runtime 1.14, 1.13.1 and 1.12.1 and lower
> ### CUDNN 8.5.0.96 (Windows)
> ### Microsoft.ML.OnnxRuntime.Managed 1.15.1 (since it is a dependency for your package)
> **the only difference is if i load 1.14 onnx.gpu i get this error:** `System.EntryPointNotFoundException: "Unable to find an entry point named 'OrtSessionOptionsAppendExecutionProvider_CUDA' in DLL 'onnxruntime'."`
> 
> **and if i load <1.13.1 i get this:** `System.TypeInitializationException: "The type initializer for 'Microsoft.ML.OnnxRuntime.NativeMethods' threw an exception." `
> 
> _Do onnx.runtime and onnx.runtime.gpu need always the same versions?_ if i take onnx.runtime.gpu 1.12.1 and onnx.runtime 1.13.1, my program is shown up, but if i start my function it crashs without any Exception. Here the line where it crashs, i tried to catch it but they wont throw any exception. They just kill my Program:
> 
> ```
> graphics.CopyFromScreen(wh.Item2.X, wh.Item2.Y, 0, 0, new System.Drawing.Size(wh.Item1.X, wh.Item1.Y));
> var image = v8.ConvertBitmapToImageSharpImage(screenshot);
> Prediction[] predictions = null;
> try
> {
>     predictions = v8.yolo.Predict(image); // After reach this point it kills my program
> }catch (Exception ex) 
> { }
> ```
> 
> 
> 您推荐哪个版本的软件包？我也试过了
> 
> ### CUDA 11.6，
> ### onnx.runtime.gpu 1.14、1.13.1和1.12.1及更低版本
> ### onnx.runtime 1.14、1.13.1和1.12.1及更低版本
> ### CUDNN 8.5.0.96（Windows）
> ### Microsoft.ML. OnnxServer.Managed 1.15.1（因为它是您的包的依赖项）
> 唯一的区别是，如果我加载1.14 onnx.gpu，我得到这个错误：`System.EntryPointNotFoundException: "Unable to find an entry point named 'OrtSessionOptionsAppendExecutionProvider_CUDA' in DLL 'onnxruntime'."`
> 
> 如果我加载1.13.1，我得到这个：`System.TypeInitializationException: "The type initializer for 'Microsoft.ML.OnnxRuntime.NativeMethods' threw an exception." `
> 
> onnx.runtime. gpu和onnx.runtime.gpu需要总是相同的版本吗？ 如果我使用onnx.runtime.gpu 1.12.1和onnx.runtime 1.13.1，我程序会显示出来，但是如果我启动我的函数，它会崩溃，没有任何异常。 这里是它崩溃的地方，我试图抓住它，但他们不会抛出任何异常。他们只是杀了我的程序：
> 
> ```
> graphics.CopyFromScreen（wh.Item2.X，wh.Item2.Y，0，0，new System.Drawing.Size（wh.Item1.X，wh.Item1.Y））;
> var image = v8.ConvertBitmapToImageSharpImage（screenshot）;
> Prediction[] predictions = null;
> 尝试
> {
>     predictions = v8.yolo.Predict（image）; //在到达这一点后，它会杀死我的程序
> }catch（Exception ex） 
> - -
> ```

May I ask how to solve this problem？
