### ISSUE TITLE
System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by Th3Suspect** [sstainba/Yolov8.Net#18]
Hey guys, sorry for stupidness(i'm newbie to this)

I'm trying to use custom self-made dataset

and getting this error:

`System.ArgumentOutOfRangeException: "Specified argument was out of the range of valid values. Arg_ParamName_Name"`

On 
`using var yolo = YoloV8Predictor.Create("Assets/test.onnx");`

onnx created with CLI:
`detect train data=data.yaml model=yolov8n.yaml epochs=1 imgsz=640`
`yolo export model=best.pt format=onnx opset=15`

paramName: Number of labels provided exceeds output dimensions of model(i think this is the issue, but i'm not sure what to do to fix it)

**Comment by sstainba** [comment]
When you export your model, you should export it with the imgsz=640 parameter as well, fyi.  If you are using a set of labels other than the standard COCO set (and it looks like you are), you have to provide them in the constructor for the predictor.  This is mentioned in the readme above the first line of code.

**Comment by Th3Suspect** [comment]
> When you export your model, you should export it with the imgsz=640 parameter as well, fyi. If you are using a set of labels other than the standard COCO set (and it looks like you are), you have to provide them in the constructor for the predictor. This is mentioned in the readme above the first line of code.

Thanks a lot, didnt noticed labels. Thanks a lot! And thanks for advice about imgsz=640 parameter for export, will do. Sorry that disturbed you and thanks again for help :)
