### ISSUE TITLE
several exceptions with cuda and onnx (gpu)

### ISSUE THREAD

**Issue by Steven-L-42** [sstainba/Yolov8.Net#21]
_Which version you recommend for your package?_ 
i tried now also 

### Microsoft.ML.OnnxRuntime.Managed 1.15.1 (since it is a dependency for your package)

**the only difference is if i load 1.14 onnx.gpu i get this error:** `System.EntryPointNotFoundException: "Unable to find an entry point named 'OrtSessionOptionsAppendExecutionProvider_CUDA' in DLL 'onnxruntime'."`

**and if i load <1.13.1 i get this:** `System.TypeInitializationException: "The type initializer for 'Microsoft.ML.OnnxRuntime.NativeMethods' threw an exception."
`

_Do onnx.runtime and onnx.runtime.gpu need always the same versions?_
if i take onnx.runtime.gpu 1.12.1 and onnx.runtime 1.13.1, my program is shown up, but if i start my function it crashs without any Exception.
Here the line where it crashs, i tried to catch it but they wont throw any exception. They just kill my Program: 

```
graphics.CopyFromScreen(wh.Item2.X, wh.Item2.Y, 0, 0, new System.Drawing.Size(wh.Item1.X, wh.Item1.Y));
var image = v8.ConvertBitmapToImageSharpImage(screenshot);
Prediction[] predictions = null;
try
{
    predictions = v8.yolo.Predict(image); // After reach this point it kills my program
}catch (Exception ex) 
{ }
```

**Comment by sstainba** [comment]
Nvidia has a table that shows which version of CUDNN corresponds to a given version of the CUDA drivers.  You need to make sure those match.

**Comment by Steven-L-42** [comment]
i used this: https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html

i think its the same..

**Comment by sstainba** [comment]
You need to install CUDA Toolkit v 11.6 and CUDNN 8.9.2 for CUDA 11.x.  
https://docs.nvidia.com/deeplearning/cudnn/support-matrix/index.html#cudnn-cuda-hardware-versions
Note the part here about Zlib:
https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html#install-windows

Apparently NVIDIA's installation instructions aren't quite correct.  Copy the lib, bin, include folders from the CUDNN zip into the corresponding folders for the toolkit.  And add the Toolkit's bin folder to your path.
See https://github.com/microsoft/onnxruntime/issues/12488

**Comment by Steven-L-42** [comment]
Problem was solved. I just had to uninstall the OnnxRuntime nuget package and leave the OnnxRuntime.GPU installed. Possibly Visual Studio recovery is causing these issues while installing these packages...

But is it normal that only about 15-25% of the GPU is used?
Also, it looks like the CPU is being used at 50% as well.
I don't really understand the connection and why the GPU is not fully used. I only achieve about 150ms with the YoloV8n model. This should probably be much faster.

No side programs are running during this test.

**Comment by sstainba** [comment]
The only part of this that runs on the GPU is the inference.  The rest of the code still has to run on the CPU.  And I can't say what is "normal" because I have no idea what you are doing.  Your expectation that this would use the "entire GPU" says to me that you have a misunderstanding of the work load or possible what is actually happening.
Regarding the 150ms, as mentioned in other posts on here and in the readme at the top, loading the model into the GPU is not very fast and so single inferences can be slow, especially depending on how large the model is.  Subsequent inferences against the some predictor are significantly faster.  See #13
