### ISSUE TITLE
Load model on GPU: Exception OrtSessionOptionsAppendExecutionProvider_CUDA

### ISSUE THREAD

**Issue by Chewbathra** [sstainba/Yolov8.Net#22]
Hello,

Thanks for your package that work well !

When i try to load the model on GPU, i have an exception saying :
![image](https://github.com/sstainba/Yolov8.Net/assets/10773783/40736429-9891-4be7-9869-d211fd24103f)

Do you already had this exception ?

I have cuda V12.0 with CUDNN installed (if I didnt failed installation).
![image](https://github.com/sstainba/Yolov8.Net/assets/10773783/d4896920-ba6b-4b5e-b96a-ef3f8e976928)

Thanks for your help !

**Comment by sstainba** [comment]
v12 isn't compatible with the runtime.  Please use CUDA Dev pack and CUDNN v 11.
________________________________
From: Schupbach Loïc ***@***.***>
Sent: Tuesday, June 27, 2023 7:48:22 AM
To: sstainba/Yolov8.Net ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [sstainba/Yolov8.Net] Load model on GPU: Exception OrtSessionOptionsAppendExecutionProvider_CUDA (Issue #22)


Hello,

Thanks for your package that work well !

When i try to load the model on GPU, i have an exception saying :
[image]<https://user-images.githubusercontent.com/10773783/249139510-40736429-9891-4be7-9869-d211fd24103f.png>

Do you already had this exception ?

I have cuda V12.0 with CUDNN installed (if I didnt failed installation).
[image]<https://user-images.githubusercontent.com/10773783/249140017-d4896920-ba6b-4b5e-b96a-ef3f8e976928.png>

Thanks for your help !
