### ISSUE TITLE
Image is resized after prediction

### ISSUE THREAD

**Issue by bodstersll** [sstainba/Yolov8.Net#23]
After using ImageSharp instead of System.Drawing, image size is changed after prediction.
Here is the output using **System.Drawing**:
![c804fa62697a0bef5f48c84d01f1dec](https://github.com/sstainba/Yolov8.Net/assets/122479731/8157a2de-6221-4c87-b1d8-631853dcda8e)

And here is the output using **ImageSharp**:
![74c9339e92ae2472041c25779654ca0](https://github.com/sstainba/Yolov8.Net/assets/122479731/b8605594-0a2e-47e8-9d8f-54e43b0e8f28)
Why does it happen?

**Comment by wujun007** [comment]
请问 这个项目只能用yolov8训练好的模型，在该项目中加载后调用预测吗？这个项目能否实现模型训练？

**Comment by sstainba** [comment]
> 请问 这个项目只能用yolov8训练好的模型，在该项目中加载后调用预测吗？这个项目能否实现模型训练？

Please read the readme file.  When adding comments, please try to keep to the subject at hand.

**Comment by sstainba** [comment]
> After using ImageSharp instead of System.Drawing, image size is changed after prediction. Here is the output using **System.Drawing**: ![c804fa62697a0bef5f48c84d01f1dec](https://user-images.githubusercontent.com/122479731/249999339-8157a2de-6221-4c87-b1d8-631853dcda8e.png)
> 
> And here is the output using **ImageSharp**: ![74c9339e92ae2472041c25779654ca0](https://user-images.githubusercontent.com/122479731/249999624-b8605594-0a2e-47e8-9d8f-54e43b0e8f28.png) Why does it happen?

This was an oversight on my part.  I will correct this shortly to use a copy of the original so as not to permanently resize the input image.
