### ISSUE TITLE
cannot be started directly

### ISSUE THREAD

**Issue by halukmy** [sstainba/Yolov8.Net#24]
![image](https://github.com/sstainba/Yolov8.Net/assets/2916333/4a7286cf-e98c-4bb2-a515-57b0f07cdd76)

how to fix that?

**Comment by sstainba** [comment]
There's no enough information here to be useful.  This issue is a basic NET/programming issue and completely unrelated to this project.  This project outputs to an assembly for a nuget package - it's not executable.
