### ISSUE TITLE
yolov8自定义训练

### ISSUE THREAD

**Issue by wujun007** [sstainba/Yolov8.Net#25]
1.请问该项目是否可以训练自己的数据集？
2.请问该项目可以加载摄像头吗？
3.如果不能加载摄像头是否可以通过位图转换到当前项目中的image中？
4.或者可以通过emgucv或者opencvsharp进行图形转换到当前项目中的image？

**Comment by sstainba** [comment]
I don't speak Chinese but I used google translate:
1.  This project only consumes an ONNX model.  If you want to train a custom dataset, I suggest using the Yolov8 Docker image from Ultralytics.
2.  Use of the camera is up to the developer to implement.  You could need to convert the frame to a bmp and pass it to the predictors.
3.  I'm not sure I understand this question.  But, see 2 above.
4.  Again, this is up to the developer using the package to implement.

**Comment by wujun007** [comment]
Sorry, my English is not very good. How should I convert the image captured by my camera into a bitmap after converting it into the image information in the project? Are there any examples of bitmap conversion?

**Comment by sstainba** [comment]
There are many ways to to do this, but that is outside the scope of this project.  I suggest asking on stackoverflow or reddit.  You could also consult the ImageSharp documentation.
