### ISSUE TITLE
Why give the wrong code?

### ISSUE THREAD

**Issue by thisjam** [sstainba/Yolov8.Net#27]
Why give the wrong code？Too many error codes, the first line is wrong

 using var yolo = new YoloV8Predictor.Create("./assets/yolov8m.onnx");

YoloV8Predictor is private , How to new.

**Comment by thisjam** [comment]
Have you tested the readme code?

**Comment by sstainba** [comment]
It was an oversight.  Though, that should be obvious, as well as how to instantiate a new object.
