### ISSUE TITLE
yolov8n.onnx too slow than yolov5n.onnx 

### ISSUE THREAD

**Issue by esprtk** [sstainba/Yolov8.Net#29]
Yolov8n.onnx is too slow compared to what I expected when compared to yolov5n.onnx.
I mean It might be slower but I would expect it to be about 2x slower.
But it seems that yolov8n.onnx is 5 times slower than yolov5n.onnx .
I used this code to compare on the same image.

Here my Total time run with 100 loop with the same image : 

yolov5n.onnx : 9593  ms
yolov5s.onnx  : 11949 ms
yolov8n.onnx : 48384  ms

Here my test code :

``

        static long millis()
        {
            return DateTime.Now.Ticks / TimeSpan.TicksPerMillisecond;
        }

       /*    using var yolo = YoloV5Predictor.Create("C://Tractor_project/Tractor_App/MY_TRACTOR/My_ML/Assets/Weights/yolov5n.onnx" ); */

       /*    using var yolo = YoloV5Predictor.Create("C://Tractor_project/Tractor_App/MY_TRACTOR/My_ML/Assets/Weights/yolov5s.onnx" );*/

            using var yolo = YoloV8Predictor.Create("C://Tractor_project/Tractor_App/MY_TRACTOR/My_ML/Assets/Weights/yolov8n.onnx" );

            using var image = Image.Load("C://Tractor_project/Tractor_App/MY_TRACTOR/My_ML/Assets/Weights/test_img_ai.jpg");

            long T0 = millis();
            string text = "";
            for (int lap = 0; lap < 100; lap++) { 

                
            var predictions = yolo.Predict(image);
                text = "";
                foreach (var prediction in predictions)
            {
                var originalImageHeight = image.Height;
                var originalImageWidth = image.Width;

                var x = Math.Max(prediction.Rectangle.X, 0);
                var y = Math.Max(prediction.Rectangle.Y, 0);
                var width = Math.Min(originalImageWidth - x, prediction.Rectangle.Width);
                var height = Math.Min(originalImageHeight - y, prediction.Rectangle.Height);

                ////////////////////////////////////////////////////////////////////////////////////////////
                // *** Note that the output is already scaled to the original image height and width. ***
                ////////////////////////////////////////////////////////////////////////////////////////////

                // Bounding Box Text
                 text+= $"{prediction.Label.Name} [{prediction.Score}]";
                    text += "\n";
                }

            }//for

            Debug.WriteLine(text);
            Debug.WriteLine("time=" + (millis()- T0));

``

**Comment by sstainba** [comment]
So don't use it if it doesn't meet your needs.

**Comment by esprtk** [comment]
Hello Sir [sstainba](https://github.com/sstainba). Thank you for your repond.
Yolov8n is advertised as better than yolov5n when running at the same speed.
 
![223494695-0a2415c3-6b63-4afb-876a-c14171d629c1](https://github.com/sstainba/Yolov8.Net/assets/107876558/4b7aad51-ca19-4f05-bef2-552db7266b10)

Do you have any suggestions when we convert from default file yolov8n.pt to yolov8n.onnx to get running faster ?
You suggested OPSET=15 , that will make yolov8n.onnx file faster ?

**Comment by sstainba** [comment]
No, I don't.  I have nothing to do with the Ultralytics code nor the ONNX runtime.  All I did was provide a way to use the Yolo models with ONNX in .NET.  The OPSET 15 was the latest opset support by the ONNX runtime, that is the only reason I made the comment.

**Comment by esprtk** [comment]
Thanks for your great library. It really works well Sir !
Yolov8 is worth switching to if Ultralytics's ad is true, and your library is helping a lot right now .

I've been playing with yolov5 for a long time and it's time to approach Yolov8's new achievements.
I wanted to keep this discussion thread going because speed is my primary concern to make Yolov8 really worth the switch.
I think you will have better experience than me !
Do you know any solution to make Yolov8n close to (or at least 1/2) the speed of current yolov5n?

**Comment by sstainba** [comment]
Honestly I haven't bothered testing the speed.  I use custom trained models and they are plenty fast for my purposes.  I wrote this for me to use but then decided to post it in case others needed something similar.
________________________________

**Comment by esprtk** [comment]
Thanks for the feedback.
You did a great job, the reward should be for you Sir.
Hope someone and you will come back and give me some solution or advice to get me on the right track on this.

**Comment by esprtk** [comment]
Hello Sir. It me again.
I found out the position was not correct and fixed it !

Please fix this function in "Yolov5.cs" file to this : 
`
        private List<Prediction> ParseDetect(DenseTensor<float> output, SixLabors.ImageSharp.Image image)
        {
            var result = new ConcurrentBag<Prediction>();
            var (w, h) = (image.Width, image.Height); // image w and h
            var (xGain, yGain) = (ModelInputWidth / (float)w, ModelInputHeight / (float)h); // x, y gains
           // var gain = Math.Min(xGain, yGain); // gain = resized / original
            var (xPad, yPad) = ((ModelInputWidth - w * xGain) / 2, (ModelInputHeight - h * yGain) / 2); // left, right pads

            Parallel.For(0, (int)output.Length / ModelOutputDimensions, (i) =>
            {
                if (output[0, i, 4] <= Confidence) return; // skip low obj_conf results

                Parallel.For(5, ModelOutputDimensions, (j) =>
                {
                    output[0, i, j] = output[0, i, j] * output[0, i, 4]; // mul_conf = obj_conf * cls_conf
                });

                Parallel.For(5, ModelOutputDimensions, (k) =>
                {
                    if (output[0, i, k] <= MulConfidence) return; // skip low mul_conf results

                    float xMin = ((output[0, i, 0] - output[0, i, 2] / 2) - xPad) / xGain; // unpad bbox tlx to original
                    float yMin = ((output[0, i, 1] - output[0, i, 3] / 2) - yPad) / yGain; // unpad bbox tly to original
                    float xMax = ((output[0, i, 0] + output[0, i, 2] / 2) - xPad) / xGain; // unpad bbox brx to original
                    float yMax = ((output[0, i, 1] + output[0, i, 3] / 2) - yPad) / yGain; // unpad bbox bry to original

                    xMin = Utils.Clamp(xMin, 0, w - 0); // clip bbox tlx to boundaries
                    yMin = Utils.Clamp(yMin, 0, h - 0); // clip bbox tly to boundaries
                    xMax = Utils.Clamp(xMax, 0, w - 1); // clip bbox brx to boundaries
                    yMax = Utils.Clamp(yMax, 0, h - 1); // clip bbox bry to boundaries

                    Label label = Labels[k - 5];

                    var prediction = new Prediction()
                    {
                        Label = label,
                        Score = output[0, i, k],
                        Rectangle = new RectangleF(xMin, yMin, xMax - xMin, yMax - yMin)
                    };

                    result.Add(prediction);
                });
            });

            return result.ToList();
        }
`


Please fix this function in "Yolov8.cs" file to this : 

`
        protected List<Prediction> ParseOutput(DenseTensor<float> output, SixLabors.ImageSharp.Image image)
        {
            var result = new ConcurrentBag<Prediction>();
            var (w, h) = (image.Width, image.Height); // image w and h
            var (xGain, yGain) = (ModelInputWidth / (float)w, ModelInputHeight / (float)h); // x, y gains
            //var gain = Math.Min(xGain, yGain); // gain = resized / original

            var (xPad, yPad) = ((ModelInputWidth - w * xGain) / 2, (ModelInputHeight - h * yGain) / 2); // left, right pads

            //for each batch
            Parallel.For(0, output.Dimensions[0], i =>
            {
                //divide total length by the elements per prediction
                Parallel.For(0, (int)(output.Length / output.Dimensions[1]), j =>
                {

                    float xMin = ((output[i, 0, j] - output[i, 2, j] / 2) - xPad) / xGain; // unpad bbox tlx to original
                    float yMin = ((output[i, 1, j] - output[i, 3, j] / 2) - yPad) / yGain; // unpad bbox tly to original
                    float xMax = ((output[i, 0, j] + output[i, 2, j] / 2) - xPad) / xGain; // unpad bbox brx to original
                    float yMax = ((output[i, 1, j] + output[i, 3, j] / 2) - yPad) / yGain; // unpad bbox bry to original

                    xMin = Utils.Clamp(xMin, 0, w - 0); // clip bbox tlx to boundaries
                    yMin = Utils.Clamp(yMin, 0, h - 0); // clip bbox tly to boundaries
                    xMax = Utils.Clamp(xMax, 0, w - 1); // clip bbox brx to boundaries
                    yMax = Utils.Clamp(yMax, 0, h - 1); // clip bbox bry to boundaries

                    Parallel.For(0, ModelOutputDimensions - 4, l =>
                    {
                        var pred = output[i, 4 + l, j];

                        //skip low confidence values
                        if (pred < Confidence) return;

                        result.Add(new Prediction()
                        {
                            Label = Labels[l],
                            Score = pred,
                            Rectangle = new RectangleF(xMin, yMin, xMax - xMin, yMax - yMin)
                        });
                    });
                });
            });

            return result.ToList();
        }
`

It will export the correct position bounding !

**Comment by sstainba** [comment]
I hadn't noticed it was off.  I have fixed it and updated the Nuget package.  Thanks.

**Comment by esprtk** [comment]
You''re welcome.
