### ISSUE TITLE
Two error

### ISSUE THREAD

**Issue by mohamedraafat96** [sstainba/Yolov8.Net#30]
`using System.Drawing.Drawing2D;
using Yolov8Net;

namespace YOLOv8
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private void button1_Click(object sender, EventArgs e)
        {

            using var yolo = new YoloV8Predictor.Create("./assets/yolov8m.onnx");

            using var image = Image.FromFile("Assets/rufus.jpg");
            var predictions = yolo.Predict(image);
            // Draw your boxes
            using var graphics = Graphics.FromImage(image);
            foreach (var pred in predictions)
            {
                var originalImageHeight = image.Height;
                var originalImageWidth = image.Width;

                var x = Math.Max(pred.Rectangle.X, 0);
                var y = Math.Max(pred.Rectangle.Y, 0);
                var width = Math.Min(originalImageWidth - x, pred.Rectangle.Width);
                var height = Math.Min(originalImageHeight - y, pred.Rectangle.Height);

                // Bounding Box Text
                string text = $"{pred.Label.Name} [{pred.Score}]";

                using (Graphics graphics = Graphics.FromImage(image))
                {
                    graphics.CompositingQuality = CompositingQuality.HighQuality;
                    graphics.SmoothingMode = SmoothingMode.HighQuality;
                    graphics.InterpolationMode = InterpolationMode.HighQualityBicubic;

                    // Define Text Options
                    Font drawFont = new Font("consolas", 11, FontStyle.Regular);
                    SizeF size = graphics.MeasureString(text, drawFont);
                    SolidBrush fontBrush = new SolidBrush(Color.Black);
                    Point atPoint = new Point((int)x, (int)y - (int)size.Height - 1);

                    // Define BoundingBox options
                    Pen pen = new Pen(Color.Yellow, 2.0f);
                    SolidBrush colorBrush = new SolidBrush(Color.Yellow);

                    // Draw text on image 
                    graphics.FillRectangle(colorBrush, (int)x, (int)(y - size.Height - 1), (int)size.Width, (int)size.Height);
                    graphics.DrawString(text, drawFont, fontBrush, atPoint);

                    // Draw bounding box on image
                    graphics.DrawRectangle(pen, x, y, width, height);
                }
            }

        }
    }
}`

why this error occurs?

![image](https://github.com/sstainba/Yolov8.Net/assets/127994871/ff0a69ae-953a-4e54-87a1-9d09f7fb6ca1)

**Comment by sstainba** [comment]
The readme code was never corrected.  That being said, these are both very basic, and very simple errors to fix. You should really be able to figure this out without asking for help.

**Comment by esprtk** [comment]
<img width="507" alt="duplicate" src="https://github.com/sstainba/Yolov8.Net/assets/107876558/804c52f5-d03d-443e-bc37-30f688195056">


The error is obvious, you have declared 2 variables with the same name.
Let's fix it to "graphic1" and "graphic2".
