### ISSUE TITLE
Model is load successful , When I deduction programe crash.

### ISSUE THREAD

**Issue by caisongan** [sstainba/Yolov8.Net#34]
hello  can I hellp you?
 I want use gpu deduction , maybe Model is load successful because of windows Task Manager gpu was used.
but when I use  Prediction[] predictions = yoloV8Predictor.Predict(pic)   deduction,  programe crash.
By system Log crash from cuda, but try more version It's still the same:   
AppName v8.Net.exe 
  AppVersion 0.0.0.0 
  AppTimeStamp 64b073ea 
  ModuleName cudnn64_8.dll 
  ModuleVersion 6.14.11.6050 
  ModuleTimeStamp 62e9c226 
  ExceptionCode c0000409 
  FaultingOffset 000000000001420d 
  ProcessId 0xca0 
  ProcessCreationTime 0x1d9e771140acbf3 
  AppPath F:\git\Yolov8.Net-main\src\Yolov8net\bin\Debug\net6.0\v8.Net.exe 
  ModulePath C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\cudnn64_8.dll 
  IntegratorReportId 62efd072-f9ae-4003-bbc6-58db6fd2a337 
  PackageFullName  
  PackageRelativeAppId  

RUN version:
cuda_11.8.0_522.06
cudnn-windows-x86_64-8.5.0.96_cuda11-archive
onnxruntime-gpu  15.1

**Comment by sstainba** [comment]
You need to have both the CUDA drivers and the CUDNN installed.  I can't help with crashes from their drivers.  The versions mentioned in the readme work.
