### ISSUE TITLE
ResizeImage

### ISSUE THREAD

**Issue by Talla2k** [sstainba/Yolov8.Net#40]
Inference of a random image in Python leads to a change in the size of the larger side to 640, and the smaller side is proportional but a multiple of 32. Your code always has a square of 640 by 640. This is a problem, the result suffers from this.

**Comment by sstainba** [comment]
Did you look at the code?  My code interrogates the model to determine the input size and resizes to match that.

**Comment by Talla2k** [comment]
Yes, of course I looked. You actually get the height and width from the input metadata. But that's the problem. The image doesn't have to be a square, but yours is always a square.

Well, then, when exporting to ONNX, you can set the flag dynamic = True, then the metadata will have -1 for width and height. I did this, changed the picture as needed, but it doesn’t work either.

**Comment by Talla2k** [comment]
Oops...I did it))
Your code with squares produces this:
![sstainba1](https://github.com/sstainba/Yolov8.Net/assets/33942798/2131f1ad-ca03-4dd2-9343-8b3f871bf27a)

Your code with my edits and the dynamic = True parameter produces something different when exported to ONNX.
![sstainba2](https://github.com/sstainba/Yolov8.Net/assets/33942798/4e51f77a-c287-4f6f-8646-40b15d685f8b)

**Comment by sstainba** [comment]
I don't know what "Oops I did it" means. I also don't know anything about the model you're using or what edits you're talking about.  If you have a specific suggestions on something, provide details please.

**Comment by Talla2k** [comment]
1. In Python => model.export(format='onnx', opset=15, **dynamic = True**)

2. In you code new
```
 public static Image ResizeImage(Image image, int target)
        {
            if (image.Width > image.Height)
            {
                double coeff = (double)target / image.Width;
                int newh = (int) (coeff * image.Height) / 32 +1;
                newh = newh * 32;
                Bitmap bmp = new Bitmap((System.Drawing.Image)image, new System.Drawing.Size(target, newh));
                return (Image)bmp;
            }
            else
            {
                double coeff = (double)target / image.Height;
                int neww = (int)(coeff * image.Width) / 32 + 1;
                neww = neww * 32;
                Bitmap bmp = new Bitmap((System.Drawing.Image)image, new System.Drawing.Size(neww, target));
                return (Image)bmp;
            }
        }
```

3. In PredictorBase.cs =>` protected virtual DenseTensor<float>[] Inference(Image img)`
```
//resized = Extentions.ResizeImage(img, ModelInputWidth, ModelInputHeight);
resized = Extentions.ResizeImage(img, 640);
this.ModelInputHeight = resized.Height;
this.ModelInputWidth = resized.Width;
```

4. In Yolo8.cs => `protected List<Prediction> ParseOutput(DenseTensor<float> output, System.Drawing.Image image)`
not use ModelOutputDimensions. Use output.Dimensions[1]

**Comment by Talla2k** [comment]
And this always improves the result on any model. Well, unless your input image is square ;)
