### ISSUE TITLE
I triggered it “Number of labels provided exceeds output dimensions of model.”

### ISSUE THREAD

**Issue by a981676871** [sstainba/Yolov8.Net#44]
I triggered it “Number of labels provided exceeds output dimensions of model.” 
![1111111111111111](https://github.com/user-attachments/assets/d7cb44c0-67ec-4d2f-ad31-71c776258024)
May I ask the teacher to help me answer why this is happening? I have been unable to find the reason, thank you.

**Comment by sstainba** [comment]
As it says in the comment directly above the exception, your model has more outputs than the labels (classes/tags) provided.  If you are not using the standard 128 Coco labels, you need to provide your own.  This is explained in the readme.
