### ISSUE TITLE
why Gpu slower?

### ISSUE THREAD

**Issue by tondangerza** [sstainba/Yolov8.Net#5]
Hi, thank you for sharing but I have some questions.
why Gpu slower than of original version (https://github.com/ultralytics/ultralytics)?
in the original is 10-30 ms but Yolov8.net is 200-300 ms.
I use RTX3060.

**Comment by sstainba** [comment]
I don't know what you mean by "original version."  Ultralytics does not provide a .NET wrapper, so there is no other version I'm aware of.  This runs on the ONNX managed runtime, not python.  So I can't begin to compare the two.  Also, did you explicitly enable the CUDA core in the constructor?  If not, this runs on the CPU.

**Comment by tondangerza** [comment]
> I don't know what you mean by "original version." Ultralytics does not provide a .NET wrapper, so there is no other version I'm aware of. This runs on the ONNX managed runtime, not python. So I can't begin to compare the two. Also, did you explicitly enable the CUDA core in the constructor? If not, this runs on the CPU.

I understand the reason why it's slow now, which I think it's slow while loading images and converting it to tensors. If I only time the InferenceSession.Run(), it only takes 60 ms, which is the same as the python onnx.

**Comment by sstainba** [comment]
> > I don't know what you mean by "original version." Ultralytics does not provide a .NET wrapper, so there is no other version I'm aware of. This runs on the ONNX managed runtime, not python. So I can't begin to compare the two. Also, did you explicitly enable the CUDA core in the constructor? If not, this runs on the CPU.
> 
> I understand the reason why it's slow now, which I think it's slow while loading images and converting it to tensors. If I only time the InferenceSession.Run(), it only takes 60 ms, which is the same as the python onnx.

Ahhh, ok.  Are you source images the same size as your model input?  I'm wondering if the slowness is the resize or if it's just conversation to tensor.
