### ISSUE TITLE
CocoTest_CUDA fail

### ISSUE THREAD

**Issue by PetrCisar** [sstainba/Yolov8.Net#9]
Hi,

thank you for the library. It works well on CPU. I tried to use it on GPU but got this error: Microsoft.ML.OnnxRuntime.OnnxRuntimeException : [ErrorCode:RuntimeException] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1069 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "D:\Yolov8.Net-main\test\Yolov8net.test\bin\Debug\net6.0\runtimes\win-x64\native\onnxruntime_providers_cuda.dll"

I have installed CUDA dev pack but it seems that some DLLs are missing.

Regards,

Petr

**Comment by sstainba** [comment]
You need to install cudnn also

**Comment by PetrCisar** [comment]
Thank you for the aswer. I installed cudnn but still the same error. What CUDA toolkit and cudnn do you use?

**Comment by sstainba** [comment]
the CUDA and CUDNN versions both depend on your NVidia Driver version.  They all must be compatible.  There is a chart on NVidia's website.

**Comment by sstainba** [comment]
See Issue #6 (closed) where this was already reported and resolved.

**Comment by PetrCisar** [comment]
instead of ONNX.Runtime.Managed I used ONNX.Runtime.GPU and it solved the issue. But it is still slow like without the GPU acceleration. I do not see any change between CPU and GPU version.
